/**
 * The Swarm mark (M11.3).
 *
 * Generated from `MARK` in `@swarm/core` at render time, never pasted. `index.html` carried a
 * hand-copied SVG of the same drawing, which is how the splash and the header once ended up
 * wearing different robots — one drawing changed and its copies did not.
 *
 * `ART_THEME` paints in `color-mix(… var(--acc) …)`, so the mark follows the accent and the theme
 * instead of being frozen to one green.
 */
import { ART_THEME, artSvg, MARK } from "@swarm/core/art";
import { useMemo } from "react";

export interface MarkProps {
  /** Pixel size of one cell in the drawing's grid. */
  cell?: number;
  className?: string;
  title?: string;
}

export function Mark({ cell = 2, className = "", title = "Swarm" }: MarkProps) {
  const svg = useMemo(() => artSvg(MARK, ART_THEME, { cell, title }), [cell, title]);
  // No wrapper class by default: the mark sits inside `.logo` in the header, which already styles
  // it, and an extra class here would be a second place to keep in step.
  return (
    <span
      className={className || undefined}
      // biome-ignore lint/security/noDangerouslySetInnerHtml: generated by core's own artSvg
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
