/**
 * The Swarm mark (M11.3).
 *
 * Generated from `MARK` in `@swarm/core` at render time, never pasted. `index.html` carried a
 * hand-copied SVG of the same drawing, which is how the splash and the header once ended up
 * wearing different robots — one drawing changed and its copies did not.
 *
 * It renders a real `<svg>` with no wrapper element, and that matters. `.logo` is a flex row and
 * `header .logo svg` carries the width and the optical `translateY(-2px)` nudge, so the svg has to
 * *be* the flex child. Wrapped in a span, the span becomes the flex item: `align-items: center`
 * centres the wrapper while the drawing sits on its own baseline inside it, and the mark reads a
 * couple of pixels out. The same trap applies to every icon — put the svg where the layout expects
 * it, never a wrapper around it.
 *
 * `ART_THEME` paints in `color-mix(… var(--acc) …)`, so the mark follows the accent and the theme
 * instead of being frozen to one green.
 */
import { ART_THEME, artSvg, MARK } from "@swarm/core/art";
import { useMemo } from "react";

export interface MarkProps {
  /** Pixel size of one cell in the drawing's grid. */
  cell?: number;
  className?: string;
  /** Accessible name. Omit beside the word "Swarm", where the mark adds nothing to read. */
  title?: string;
}

/** Lift the viewBox and the body out of the generated markup, to put them on a real element. */
function parse(markup: string): { viewBox: string; body: string } {
  const viewBox = /viewBox="([^"]+)"/.exec(markup)?.[1] ?? "0 0 12 12";
  const body = markup.replace(/^<svg[^>]*>/, "").replace(/<\/svg>$/, "");
  return { viewBox, body };
}

export function Mark({ cell = 2, className, title }: MarkProps) {
  const { viewBox, body } = useMemo(() => parse(artSvg(MARK, ART_THEME, { cell })), [cell]);
  const inner = title ? `<title>${title}</title>${body}` : body;
  return (
    <svg
      className={className || undefined}
      viewBox={viewBox}
      shapeRendering="crispEdges"
      xmlns="http://www.w3.org/2000/svg"
      {...(title ? { role: "img" as const } : { "aria-hidden": true })}
      // biome-ignore lint/security/noDangerouslySetInnerHtml: generated by core's own artSvg
      dangerouslySetInnerHTML={{ __html: inner }}
    />
  );
}
