/**
 * Icons (M11.3).
 *
 * `icons.js` is generated at build time from the pixelarticons subset listed in `tools/build.ts`
 * and exposes `window.icon(name, size)` returning an SVG string. It is a build artifact of our own
 * making, which is why injecting it as HTML is safe here and nowhere else.
 */
import type { ReactElement } from "react";

declare global {
  interface Window {
    icon?: (name: string, size?: number, cls?: string) => string;
  }
}

/** Render one icon from the generated set. Returns null when the name is not in the subset. */
export function icon(name: string, size = 16, className?: string): ReactElement | null {
  const svg = window.icon?.(name, size, className);
  if (!svg) return null;
  return (
    // biome-ignore lint/security/noDangerouslySetInnerHtml: generated by our own tools/build.ts
    <span className="ico" dangerouslySetInnerHTML={{ __html: svg }} />
  );
}
