/**
 * Icons (M11.3).
 *
 * `icons.js` is generated at build time from the pixelarticons subset listed in `tools/build.ts`.
 * It exposes the raw path data, and this builds a real `<svg class="ph">` element from it.
 *
 * The element matters, not just the drawing: the alignment rules that put an icon on the optical
 * centre of adjacent text are written as `tbody td:not(.td-tools) > svg.ph[width="14"]`, a *direct
 * child* selector. Wrapping the icon in a span — which is what injecting the generated HTML string
 * would require — silently breaks every one of them, and icon alignment in this dashboard has been
 * re-fixed enough times already.
 */
import type { ReactElement } from "react";

declare global {
  interface Window {
    /** Icon name → inner SVG markup (paths only), from the generated icons.js. */
    ICON_PATHS?: Record<string, string>;
    /** Legacy string emitter, still used by the menus island. */
    icon?: (name: string, size?: number, cls?: string) => string;
  }
}

/** Render one icon from the generated set. Null when the name is not in the subset. */
export function icon(name: string, size = 16, className?: string): ReactElement | null {
  const paths = window.ICON_PATHS?.[name];
  if (!paths) return null;
  return (
    <svg
      className={className ? `ph ${className}` : "ph"}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="currentColor"
      shapeRendering="crispEdges"
      aria-hidden="true"
      // biome-ignore lint/security/noDangerouslySetInnerHtml: generated by our own tools/build.ts
      dangerouslySetInnerHTML={{ __html: paths }}
    />
  );
}
