/**
 * What's New (M11.13): the release notes for the version you are running.
 *
 * Opened from the settings menu, from the desktop app's Help menu (`window.swarmWhatsNew`), and
 * once by itself after an upgrade.
 *
 * The HTML comes from `tools/build.ts` rendering our own `CHANGELOG.md` at build time. It is the
 * one place the dashboard injects markup, and it is injected from a file we generate and ship —
 * never from the daemon, a repository, or anything an agent wrote.
 */
import { Modal } from "../components/Modal";
import { CHANGELOG_URL } from "../lib/external";
import type { ReleaseNote } from "../lib/releaseNotes";
import { markSeen } from "../lib/releaseNotes";

export function WhatsNew({ note, onClose }: { note: ReleaseNote; onClose: () => void }) {
  markSeen(note.version);
  return (
    <Modal
      title="What's New"
      glyph="star"
      size="wn"
      onClose={onClose}
      footer={
        <a className="wn-full" href={CHANGELOG_URL} target="_blank" rel="noopener">
          Full changelog →
        </a>
      }
    >
      <h3>Swarm {note.version}</h3>
      {note.date && <div className="date">{note.date}</div>}
      {/* biome-ignore lint/security/noDangerouslySetInnerHtml: generated by our own tools/build.ts from CHANGELOG.md */}
      <div dangerouslySetInnerHTML={{ __html: note.html }} />
    </Modal>
  );
}
