// Build the dashboard's generated assets into public/:
//   menus.js  — React island: fancy-menus provider + Swarm's menu configs (window.menus)
//   fm.css    — fancy-menus runtime stylesheet
//   icons.js  — pixelarticons as inline SVG, window.icon(name, size)
// Hand-written files (index.html, app.js, viz.js) stay as they are; no bundler touches them.
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pub = join(here, "../public");
mkdirSync(pub, { recursive: true });

// ---- icons: pixelarticons (MIT), subset listed here by stable app-facing key, emitted as
// paths only. NAME_MAP maps each key to a pixelarticons filename so the app/menus can keep
// their names while the underlying pixel-art set can be retargeted freely.
export const ICONS = [
  "squares-four",
  "timer",
  "coins",
  "pulse",
  "folder-simple",
  "folders",
  "push-pin",
  "push-pin-slash",
  "x",
  "plus",
  "dots-three",
  "dots-three-vertical",
  "keyboard",
  "play",
  "tree-structure",
  "robot",
  "coin",
  "cpu",
  "arrows-clockwise",
  "lightning",
  "clock",
  "wrench",
  "file-text",
  "git-branch",
  "git-commit",
  "arrow-left",
  "warning",
  "check",
  "copy",
  "arrow-square-out",
  "moon",
  "sun",
  "monitor",
  "gear",
  "book-open",
  "trash",
  "magnifying-glass",
  "terminal-window",
  "stack",
  "chart-bar",
  "clock-counter-clockwise",
  "brain",
  "eye",
  "pause",
  "stop",
  "broadcast",
  "plugs-connected",
  "plugs",
  "currency-dollar",
  "rows",
  "list-bullets",
  "sliders",
  "comment-text",
  "arrow-bar-left",
  "arrow-bar-right",
  "git-pull-request",
  "star",
  "arrow-right",
];
// app-facing key -> pixelarticons filename (closest pixel-art equivalent)
const NAME_MAP: Record<string, string> = {
  "squares-four": "grid-2x2-2",
  timer: "clock",
  coins: "coins",
  pulse: "chart-line",
  "folder-simple": "folder",
  folders: "files",
  "push-pin": "map-pin",
  "push-pin-slash": "map-pin",
  x: "close",
  plus: "plus",
  "dots-three": "more-horizontal",
  "dots-three-vertical": "more-vertical",
  keyboard: "keyboard",
  play: "play",
  "tree-structure": "tree",
  robot: "robot",
  coin: "coins",
  cpu: "cpu",
  "arrows-clockwise": "spinner",
  lightning: "square-power",
  clock: "clock",
  wrench: "gear",
  "file-text": "file-text",
  "git-branch": "git-branch-sharp",
  "git-commit": "git-commit-sharp",
  "arrow-left": "arrow-left",
  warning: "square-alert",
  star: "star",
  "arrow-right": "arrow-right",
  check: "check",
  copy: "copy",
  "arrow-square-out": "external-link",
  moon: "moon",
  sun: "sun",
  monitor: "monitor",
  gear: "gear",
  "book-open": "book-open",
  trash: "trash",
  "magnifying-glass": "search",
  "terminal-window": "terminal",
  stack: "files",
  "chart-bar": "chart-bar-big",
  "clock-counter-clockwise": "clock",
  brain: "robot-face",
  eye: "eye",
  pause: "pause",
  stop: "stop",
  broadcast: "rss-square",
  "plugs-connected": "plug",
  plugs: "plug",
  "currency-dollar": "dollar",
  rows: "bulletlist",
  "list-bullets": "bulletlist",
  // the plain git glyphs are 1px-sparse at 15px; the sharp variants keep their weight
  "git-pull-request": "git-pull-request-sharp",
};
const iconDir = join(here, "../node_modules/pixelarticons/svg");
const paths: Record<string, string> = {};
for (const n of ICONS) {
  const file = NAME_MAP[n] ?? n;
  const svg = readFileSync(join(iconDir, `${file}.svg`), "utf8");
  const inner = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .trim();
  paths[n] = inner;
}
writeFileSync(
  join(pub, "icons.js"),
  `// generated by tools/build.ts — pixelarticons (MIT), 24x24 grid\n` +
    `const ICON_PATHS = ${JSON.stringify(paths)};\n` +
    `window.icon = (name, size = 16, cls = "") => { const p = ICON_PATHS[name]; if (!p) return ""; ` +
    `return \`<svg class="ph \${cls}" width="\${size}" height="\${size}" viewBox="0 0 24 24" fill="currentColor" shape-rendering="crispEdges" aria-hidden="true">\${p}</svg>\`; };\n` +
    `window.ICON_NAMES = ${JSON.stringify(ICONS)};\n`,
);

// ---- fancy-menus stylesheet
copyFileSync(
  join(here, "../node_modules/@react-fancy-menus/core/dist/runtime/runtime.css"),
  join(pub, "fm.css"),
);

// ---- React island
const r = await Bun.build({
  entrypoints: [join(here, "../src/menus.tsx")],
  outdir: pub,
  target: "browser",
  format: "iife",
  minify: true,
  sourcemap: "none",
  naming: "menus.js",
  define: { "process.env.NODE_ENV": '"production"' },
});
if (!r.success) {
  for (const m of r.logs) console.error(m);
  process.exit(1);
}
console.log(`web: built icons.js (${ICONS.length} icons), fm.css, menus.js`);
