// Build the dashboard's generated assets into public/:
//   menus.js  — React island: fancy-menus provider + Swarm's menu configs (window.menus)
//   fm.css    — fancy-menus runtime stylesheet
//   icons.js  — Phosphor (regular) icons as inline SVG, window.icon(name, size)
// Hand-written files (index.html, app.js, viz.js) stay as they are; no bundler touches them.
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pub = join(here, "../public");
mkdirSync(pub, { recursive: true });

// ---- icons: one family (Phosphor regular), subset listed here, emitted as paths only.
export const ICONS = [
  "squares-four",
  "timer",
  "coins",
  "pulse",
  "folder-simple",
  "folders",
  "push-pin",
  "push-pin-slash",
  "x",
  "plus",
  "dots-three",
  "dots-three-vertical",
  "keyboard",
  "play",
  "tree-structure",
  "robot",
  "coin",
  "cpu",
  "arrows-clockwise",
  "lightning",
  "clock",
  "wrench",
  "file-text",
  "git-branch",
  "git-commit",
  "arrow-left",
  "warning",
  "check",
  "copy",
  "arrow-square-out",
  "moon",
  "sun",
  "monitor",
  "gear",
  "book-open",
  "trash",
  "magnifying-glass",
  "terminal-window",
  "stack",
  "chart-bar",
  "clock-counter-clockwise",
  "brain",
  "eye",
  "pause",
  "stop",
  "broadcast",
  "plugs-connected",
  "plugs",
  "currency-dollar",
  "rows",
  "list-bullets",
];
const iconDir = join(here, "../node_modules/@phosphor-icons/core/assets/regular");
const paths: Record<string, string> = {};
for (const n of ICONS) {
  const svg = readFileSync(join(iconDir, `${n}.svg`), "utf8");
  const inner = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .trim();
  paths[n] = inner;
}
writeFileSync(
  join(pub, "icons.js"),
  `// generated by tools/build.ts — Phosphor Icons (MIT), regular weight\n` +
    `const ICON_PATHS = ${JSON.stringify(paths)};\n` +
    `window.icon = (name, size = 16, cls = "") => { const p = ICON_PATHS[name]; if (!p) return ""; ` +
    `return \`<svg class="ph \${cls}" width="\${size}" height="\${size}" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true">\${p}</svg>\`; };\n` +
    `window.ICON_NAMES = ${JSON.stringify(ICONS)};\n`,
);

// ---- fancy-menus stylesheet
copyFileSync(
  join(here, "../node_modules/@react-fancy-menus/core/dist/runtime/runtime.css"),
  join(pub, "fm.css"),
);

// ---- React island
const r = await Bun.build({
  entrypoints: [join(here, "../src/menus.tsx")],
  outdir: pub,
  target: "browser",
  format: "iife",
  minify: true,
  sourcemap: "none",
  naming: "menus.js",
  define: { "process.env.NODE_ENV": '"production"' },
});
if (!r.success) {
  for (const m of r.logs) console.error(m);
  process.exit(1);
}
console.log(`web: built icons.js (${ICONS.length} icons), fm.css, menus.js`);
